In [1]:
import pandas as pd

In [2]:
loc1 = pd.read_csv("trace_data/location_pt1.csv")
loc2 = pd.read_csv("trace_data/location_pt2.csv")
loc3 = pd.read_csv("trace_data/location_pt3.csv")
loc4 = pd.read_csv("trace_data/location_pt4.csv")
loc5 = pd.read_csv("trace_data/location_pt5.csv")
loc6 = pd.read_csv("trace_data/location_pt6.csv")

In [6]:
all_loc = pd.concat([loc1, loc2, loc3, loc4, loc5, loc6])

In [11]:
all_loc.groupby("recid").count()

,personid,hhid,pernum,tripnum,accuracy,heading,speed,collected_at_date,collected_at_time,lat,lng
recid,,,,,,,,,,,
1,41,41,41,41,41,40,40,41,41,41,41
2,27,27,27,27,27,26,26,27,27,27,27
3,30,30,30,30,30,28,28,30,30,30,30
4,39,39,39,39,39,38,38,39,39,39,39
5,38,38,38,38,38,37,37,38,38,38,38
...,...,...,...,...,...,...,...,...,...,...,...
81109,27,27,27,27,27,26,26,27,27,27,27
81110,31,31,31,31,31,30,30,31,31,31,31
81111,16,16,16,16,16,15,15,16,16,16,16
81112,22,22,22,22,22,22,22,22,22,22,22
81113,27,27,27,27,27,26,26,27,27,27,27

In [12]:
all_loc[all_loc["recid"]==1]

,personid,recid,hhid,pernum,tripnum,accuracy,heading,speed,collected_at_date,collected_at_time,lat,lng
857,19100000101,1,191000001,1,1,10.0,74.0,0.0,5/7/2019 7:28,5/7/2019 7:28,47.51448,-122.30355
4572,19100000101,1,191000001,1,1,10.0,328.0,1.0,5/7/2019 7:02,5/7/2019 7:02,47.60575,-122.32166
7236,19100000101,1,191000001,1,1,10.0,332.0,2.0,5/7/2019 7:18,5/7/2019 7:18,47.51769,-122.30288
9561,19100000101,1,191000001,1,1,10.0,328.0,5.0,5/7/2019 7:02,5/7/2019 7:02,47.60645,-122.32240
11689,19100000101,1,191000001,1,1,10.0,269.0,6.0,5/7/2019 7:00,5/7/2019 7:00,47.60171,-122.31704
11690,19100000101,1,191000001,1,1,10.0,242.0,6.0,5/7/2019 7:04,5/7/2019 7:04,47.60638,-122.32292
11691,19100000101,1,191000001,1,1,10.0,231.0,6.0,5/7/2019 7:05,5/7/2019 7:05,47.60440,-122.32747
13541,19100000101,1,191000001,1,1,10.0,324.0,8.0,5/7/2019 7:00,5/7/2019 7:00,47.60191,-122.31801
13542,19100000101,1,191000001,1,1,10.0,333.0,8.0,5/7/2019 7:01,5/7/2019 7:01,47.60499,-122.32116
16406,19100000101,1,191000001,1,1,10.0,157.0,10.0,5/7/2019 7:05,5/7/2019 7:05,47.60330,-122.32772
17630,19100000101,1,191000001,1,1,10.0,349.0,14.0,5/7/2019 7:14,5/7/2019 7:14,47.50806,-122.29131
19146,19100000101,1,191000001,1,1,10.0,335.0,17.0,5/7/2019 7:14,5/7/2019 7:14,47.51023,-122.29245
19486,19100000101,1,191000001,1,1,10.0,130.0,28.0,5/7/2019 7:09,5/7/2019 7:09,47.54970,-122.31437
19487,19100000101,1,191000001,1,1,10.0,148.0,28.0,5/7/2019 7:10,5/7/2019 7:10,47.54338,-122.30611
19795,19100000101,1,191000001,1,1,10.0,186.0,27.0,5/7/2019 7:06,5/7/2019 7:06,47.59376,-122.32108
19796,19100000101,1,191000001,1,1,10.0,188.0,27.0,5/7/2019 7:08,5/7/2019 7:08,47.56500,-122.32143
20374,19100000101,1,191000001,1,1,10.0,174.0,26.0,5/7/2019 7:07,5/7/2019 7:07,47.58390,-122.32026
20375,19100000101,1,191000001,1,1,10.0,182.0,26.0,5/7/2019 7:08,5/7/2019 7:08,47.57451,-122.32001
20376,19100000101,1,191000001,1,1,10.0,150.0,26.0,5/7/2019 7:09,5/7/2019 7:09,47.55634,-122.32018
20902,19100000101,1,191000001,1,1,10.0,160.0,30.0,5/7/2019 7:11,5/7/2019 7:11,47.52781,-122.29334
22285,19100000101,1,191000001,1,1,10.0,189.0,24.0,5/7/2019 7:06,5/7/2019 7:06,47.59309,-122.32124
22475,19100000101,1,191000001,1,1,10.0,136.0,23.0,5/7/2019 7:06,5/7/2019 7:06,47.60024,-122.32347
65755,19100000101,1,191000001,1,1,5.0,152.0,24.0,5/7/2019 7:12,5/7/2019 7:12,47.51506,-122.28738
66590,19100000101,1,191000001,1,1,5.0,161.0,26.0,5/7/2019 7:12,5/7/2019 7:12,47.52004,-122.29018
66591,19100000101,1,191000001,1,1,5.0,152.0,26.0,5/7/2019 7:12,5/7/2019 7:12,47.51318,-122.28595
66915,19100000101,1,191000001,1,1,5.0,140.0,28.0,5/7/2019 7:11,5/7/2019 7:11,47.53653,-122.29848
68265,19100000101,1,191000001,1,1,5.0,267.0,15.0,5/7/2019 7:14,5/7/2019 7:14,47.50740,-122.29040
68972,19100000101,1,191000001,1,1,5.0,260.0,12.0,5/7/2019 7:13,5/7/2019 7:13,47.50780,-122.28347
70537,19100000101,1,191000001,1,1,5.0,199.0,10.0,5/7/2019 7:13,5/7/2019 7:13,47.50795,-122.28282
72372,19100000101,1,191000001,1,1,5.0,343.0,6.0,5/7/2019 7:16,5/7/2019 7:16,47.51676,-122.29668
73673,19100000101,1,191000001,1,1,5.0,253.0,3.0,5/7/2019 7:16,5/7/2019 7:16,47.51687,-122.29728
73674,19100000101,1,191000001,1,1,5.0,228.0,3.0,5/7/2019 7:17,5/7/2019 7:17,47.51615,-122.29810
73675,19100000101,1,191000001,1,1,5.0,282.0,3.0,5/7/2019 7:17,5/7/2019 7:17,47.51585,-122.30104
80268,19100000101,1,191000001,1,1,5.0,218.0,1.0,5/7/2019 7:19,5/7/2019 7:19,47.51712,-122.30345
80269,19100000101,1,191000001,1,1,5.0,175.0,1.0,5/7/2019 7:19,5/7/2019 7:19,47.51685,-122.30359
80270,19100000101,1,191000001,1,1,5.0,183.0,1.0,5/7/2019 7:20,5/7/2019 7:20,47.51626,-122.30348
80271,19100000101,1,191000001,1,1,5.0,211.0,1.0,5/7/2019 7:21,5/7/2019 7:21,47.51580,-122.30398
80272,19100000101,1,191000001,1,1,5.0,156.0,1.0,5/7/2019 7:22,5/7/2019 7:22,47.51523,-122.30383
133416,19100000101,1,191000001,1,1,21.0,155.0,9.0,5/7/2019 7:05,5/7/2019 7:05,47.60357,-122.32784
162865,19100000101,1,191000001,1,1,30.0,146.0,1.0,5/7/2019 7:23,5/7/2019 7:23,47.51519,-122.30340
186368,19100000101,1,191000001,1,1,-1.0,NaN,NaN,5/7/2019 6:59,5/7/2019 6:59,47.60174,-122.30562

In [9]:
# all_loc.to_csv("psrc_trajectory_2019.csv")